version: "3.9"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=secret
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=todolist
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    # environment:
    #   - DB_SOURCE=mysql://todo:secret@tcp(mysql:3306)/todolist
    depends_on:
      - mysql
    entrypoint:
      [
        "/app/wait-for.sh",
        "mysql:3306",
        "--",
        "/app/main"
        # "/app/start.sh"
      ]
    command: [ "/app/main" ]

