version: "3.9"
services:
  mysql:
    image: mysql:8.1
    environment:
      - MYSQL_USER=todo
      - MYSQL_PASSWORD=secret
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=todolist
      - MYSQL_ROOT_PASSWORD=secret
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_SOURCE=mysql://todo:secret@tcp(mysql:3306)/todolist
    depends_on:
      - mysql
    entrypoint:
      [
        "/app/wait-for.sh",
        "mysql:3306",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]